spring:
  application:
    name: rest-with-springboot-with-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springboot_with_java_erudio?useTimezone=true&serverTimezone=UTC&connectTimeout=30000&socketTimeout=30000
    username: root
    password: 76281y00
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  logging:
    level:
      root: WARN
      #io.github.yuricsg: DEBUG